import os
import tempfile
import torch
import cv2
from PIL import Image
import torchvision.transforms as transforms
from ai_model.UniversalFakeDetect.models import get_model
from PIL import Image, ExifTags

# Match the original CLIP preprocessing used by UniversalFakeDetect
MEAN = [0.48145466, 0.4578275, 0.40821073]
STD = [0.26862954, 0.26130258, 0.27577711]

# Load model once when Flask starts
model = get_model("CLIP:ViT-L/14")
state_dict = torch.load(
    "ai_model/UniversalFakeDetect/pretrained_weights/fc_weights.pth",
    map_location="cpu"
)
model.fc.load_state_dict(state_dict)
model.eval()

transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=MEAN, std=STD),
])


def detect_image(image_path):
    """
    Detect whether one image is likely AI-generated.
    Returns a fake probability between 0 and 1.
    """
    img = Image.open(image_path).convert("RGB")
    img = transform(img).unsqueeze(0)

    with torch.no_grad():
        output = model(img)
        score = torch.sigmoid(output).item()

    return score


def extract_video_frames(video_path, max_frames=8):
    """
    Extract several evenly spaced frames from a video.
    Returns a list of temporary image paths.
    """
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        raise ValueError("Unable to open video file")

    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    if total_frames <= 0:
        raise ValueError("No frames found in video")

    frame_paths = []

    # Choose evenly spaced frame positions
    frame_indices = [
        int(i * total_frames / max_frames)
        for i in range(max_frames)
    ]

    for idx in frame_indices:
        cap.set(cv2.CAP_PROP_POS_FRAMES, idx)
        success, frame = cap.read()

        if success:
            # Convert OpenCV BGR to RGB
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
            image = Image.fromarray(frame_rgb)

            temp_file = tempfile.NamedTemporaryFile(
                delete=False,
                suffix=".jpg"
            )
            image.save(temp_file.name)
            frame_paths.append(temp_file.name)

    cap.release()
    return frame_paths


def detect_video(video_path, max_frames=8):
    """
    Detect whether a video is likely AI-generated by checking sampled frames.
    Returns average fake probability and frame-level scores.
    """
    frame_paths = extract_video_frames(video_path, max_frames=max_frames)

    if not frame_paths:
        raise ValueError("No valid frames extracted from video")

    frame_scores = []

    for frame_path in frame_paths:
        score = detect_image(frame_path)
        frame_scores.append(score)

    # Clean temporary frame files
    for frame_path in frame_paths:
        try:
            os.remove(frame_path)
        except OSError:
            pass

    avg_score = sum(frame_scores) / len(frame_scores)

    return {
        "average_fake_probability": avg_score,
        "frame_scores": frame_scores,
        "frames_checked": len(frame_scores)
    }


def classify_score(score):
    """
    Convert probability into user-friendly label.
    Do not make it too absolute because AI detection is not 100% accurate.
    """
    if score >= 0.7:
        return "High AI-generated risk"
    elif score >= 0.4:
        return "Uncertain / Needs review"
    else:
        return "Low AI-generated risk"
    

def check_image_metadata(image_path):
    result = {
        "has_exif": False,
        "camera_make": None,
        "camera_model": None,
        "datetime": None,
        "software": None,
        "warning": []
    }

    try:
        img = Image.open(image_path)
        exif_data = img.getexif()

        if not exif_data:
            result["warning"].append("No EXIF metadata found. The image may be edited, compressed, downloaded, or AI-generated.")
            return result

        result["has_exif"] = True

        for tag_id, value in exif_data.items():
            tag = ExifTags.TAGS.get(tag_id, tag_id)

            if tag == "Make":
                result["camera_make"] = str(value)
            elif tag == "Model":
                result["camera_model"] = str(value)
            elif tag == "DateTime":
                result["datetime"] = str(value)
            elif tag == "Software":
                result["software"] = str(value)

        if result["software"]:
            result["warning"].append(f"Software metadata found: {result['software']}. This may indicate editing or export processing.")

        if not result["camera_make"] and not result["camera_model"]:
            result["warning"].append("No camera device information found.")

        return result

    except Exception as e:
        result["warning"].append(f"Metadata check failed: {str(e)}")
        return result